[package]
name = "riw"
version = "0.1.0"
edition = "2021"

[dependencies]
glam = "*"
rand = "*"
rayon = "*"

# [profile.release]
# lto = "fat"
# panic = 'abort'
# opt-level = 3
# codegen-units = 1
# incremental = false
# debug = false
# overflow-checks = false
# debug-assertions = false
#
